### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by willf** [bits-and-blooms/bloom#56]
I am not writing Go code anymore. Would someone like to take over as maintainer? @lemire ?

**Comment by moredure** [comment]
@willf, please check https://github.com/willf/bloom/pull/57

**Comment by lemire** [comment]
I'd be happy to act as maintainer if you'd like.

**Comment by willf** [comment]
@lemire Thanks! Glad to move this repo to you, or  to an org, or leave as is, as you prefer

**Comment by lemire** [comment]
@willf The Bloom and bits thing seemed sexy, no?

https://github.com/bits-and-blooms

It makes a whole lot of sense to me to have an org dedicated to such data structures.

**Comment by willf** [comment]
The repositories have been moved to https://github.com/bits-and-blooms (and links should redirect). 

Thank you, @lemire, for taking over the maintenance of this package!
