### ISSUE TITLE
Issue when importing package from master branch

### ISSUE THREAD

**Issue by moredure** [bits-and-blooms/bloom#60]
when I importing bloom from master branch `go get -u github.com/bits-and-blooms/bloom@master` error appear that bitset package has invalid go.mod module github.com/willf/bitset

**Comment by moredure** [comment]
If I importing not from master branch I can't see latest changes on memory optimisation you've done

**Comment by moredure** [comment]
```
go get -u github.com/bits-and-blooms/bloom@master
go get: github.com/bits-and-blooms/bitset@none updating to
        github.com/bits-and-blooms/bitset@v1.1.11: parsing go.mod:
        module declares its path as: github.com/willf/bitset
                but was required as: github.com/bits-and-blooms/bitset
```

**Comment by moredure** [comment]
update go.mod inside bits-and-bloom/bitset

**Comment by lemire** [comment]
Hopefully this has been resolved. Reopen if the problem remains.
