### ISSUE TITLE
Question for hashing strings and order inside it

### ISSUE THREAD

**Issue by robsztal** [bits-and-blooms/bloom#64]
Hey,

I have a question if it is possible to hash strings not depending on the order of strings? I mean 

hash("black cat") = hash("cat black") 

this generates false negatives because changing order of sentence results in totally different hash. Is there any option for it? Maybe splitting sentences and combining hashed strings?

Thank you for any response.

**Comment by robsztal** [comment]
If it is possible I would like to implement that functionality as AddStringsNotInOrder function that uses splitign and usmming hashes

**Comment by willf** [comment]
I'm not the maintainer any more, but I suspect this is beyond the scope of this library, and it would be better if the calling program would do the collation before the hash call.

**Comment by lemire** [comment]
@willf is correct, it is outside the scope of the library to handle such an issue.

You can hash each word separately, and define the total hash function as a sum (for example):
```
totalhash("black cat") = hash("black") + hash("cat")
```

It is an interesting issue, but unrelated to bloom filters... it is a generic challenge.
