### ISSUE TITLE
Max number of elements

### ISSUE THREAD

**Issue by hurek** [bits-and-blooms/bloom#73]
What is max number of elements in bloom filter? If it will be 200-300 millions - its ok?

**Comment by saifat29** [comment]
@hurek It all depends on how much RAM your system has, try filling the filter and see how much memory it consumes on your system, keep doing it until you either reach your RAM capacity for your requirement (200-300 million) entries.

**Comment by lemire** [comment]
Supporting 200 million elements is doable. If you encounter a problem, please open an issue.
