### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [bits-and-blooms/bloom#77]
Hey there!

I belong to an open source security research community, and a member (@akincibor) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by lemire** [comment]
Done.

**Comment by JamieSlome** [comment]
@lemire - thanks for your diligence, you should have received an e-mail about 6 hours ago 👍 

Just for reference, the report we received can also be found here:
https://huntr.dev/bounties/cab50e44-0995-4ac1-a5d5-889293b9704f/
